# Generated by Django 4.2.13 on 2024-06-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_project_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdetails',
            name='institution',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicdetails',
            name='university',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
    ]
