# Generated by Django 4.2.13 on 2024-07-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_academicdetails_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='urlfield',
            field=models.URLField(default=1234),
            preserve_default=False,
        ),
    ]
