# Generated by Django 4.2.13 on 2024-07-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userdetails_urlfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='dob',
            field=models.DateField(default='2007-03-08'),
        ),
    ]
